# .github/actions/build-and-upload/action.yml
name: 'Build and Upload Cloud Function'
description: 'Builds function code and uploads it to GCS'
inputs:
  working-directory:
    description: 'The working directory of the application'
    required: true
  code-bucket:
    description: 'The GCS bucket to upload the code to'
    required: true
  gcp-project-id:
     description: "GCP Project ID"
     required: true
  function-artifact-name:
    description: 'The name of the function artifact'
    required: true
runs:
  using: "composite"
  steps:
    - name: Zip function code
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        zip -r ${{ inputs.function-artifact-name }}.zip .
    - name: Upload Artifacts to GCS
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        gsutil cp ${{ inputs.function-artifact-name }}.zip gs://${{ inputs.gcp-project-id }}-${{ inputs.code-bucket }}