# This file contains a list of Google Cloud APIs that are required for the project.
# These APIs are used in the CI/CD pipeline and Terraform configurations.
apis:
  - artifactregistry.googleapis.com
  - cloudbuild.googleapis.com
  - cloudfunctions.googleapis.com
  - cloudresourcemanager.googleapis.com
  - containerregistry.googleapis.com
  - pubsub.googleapis.com
  - storage-api.googleapis.com
  - storage-component.googleapis.com
  - storage.googleapis.com
  - translate.googleapis.com
  - texttospeech.googleapis.com  